version: '3'

services:

  php-apache:
    image: punimeister/php-apache:latest
    restart: on-failure
    environment:
      APACHE_ACCESS_FILE: .htaccess.docker .htaccess
      APP_HOME_DIR: /var/www/html
      PUBLIC_DIR: /public
      REMOTE_DEBUG: 0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/root/.local/share/mkcert
      - ./web:/var/www/html
    working_dir: /var/www/html
